config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :shops
    collection do
      get 'count' => 'users#count', defaults: { format: :json }
    end

    member do
      get 'name', defaults: { format: :json }
    end
  end

  root to: "users#index"

end

app/models/shop.rb
class Shop
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String

  belongs_to :shop

  index shop_id: 1
end

app/models/user.rb
class User
  GENDERS = ['male', 'female', 'others']

  include Mongoid::Document
  include Mongoid::Timestamps
  field :firstname, type: String
  field :lastname, type: String
  field :age, type: Integer
  field :gender, type: String
  field :address, type: Hash, default: {}

  has_one :shop, dependent: :destroy

  validates :firstname, presence: true
  validates :lastname,  presence: true
  validates :age, format: { with: /\A[1-9]\d*\z/i }
  validates :gender, inclusion: User::GENDERS
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :name]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def count
    respond_to do |format|
      format.json
    end
  end

  def name
    respond_to do |format|
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :age, :gender,
                                   address: [:county, :address_1, :address_2])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blank</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="user_app">

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, User::GENDERS.collect { |gender| [gender, gender] }, include_blank: false  %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= text_field_tag "user[address][county]" %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br>
    <%= text_field_tag "user[address][address_1]" %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br>
    <%= text_field_tag "user[address][address_2]" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<user-form uid="'<%= @user.id %>'"></user-form>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Age</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr ng-controller="userNavigationController">
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a ng-click="showForm()">Edit</a></td>
        <td><user-form uid="'<%= user.id %>'" ng-show="showUserForm"></user-form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>
<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>
<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>
<p>
  <strong>County:</strong>
  <%= @user.address[:county] %>
</p>
<p>
  <strong>Address 1:</strong>
  <%= @user.address[:address_1] %>
</p>
<p>
  <strong>Address 2:</strong>
  <%= @user.address[:address_2] %>
</p>

<div ng-controller="userNavigationController">
  <user-form uid="'<%= @user.id %>'" ng-show="showUserForm"></user-form>
  <a ng-click="showForm()">Edit</a> |
</div>

<%= link_to 'Back', users_path %>